name: ChatMonitor
version: '${project.version}'
main: dev.michaelh.chatmonitor.ChatMonitor
api-version: '1.20'

commands:
  reloadconfig:
    description: Reloads the config
    usage: /<command>
    permission: chatmonitor.reload
  staffchat:
    description: Sends a message to all staff
    usage: /<command> <message>
    permission: chatmonitor.staffchat
  adminchat:
    description: Sends a message to all admins
    usage: /<command> <message>
    permission: chatmonitor.adminchat